project:
  type: book

book:
  title: "R for Data Analysis"
  author: "Trevor French"
  date: "8/16/2022"
  cover-image: cover.png
  repo-url: https://github.com/TrevorFrench/R-for-Data-Analysis
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  open-graph: true
  twitter-card: 
    site: "@TrvrFrnch"
  chapters:
    - part: index.qmd
      chapters:
      - p0c1-what-is-r.qmd
      - p0c2-what-is-data-analysis.qmd
      - p0c3-setup.qmd
    - part: p1-fundamentals.qmd
      chapters:
        - p1c1-r-studio.qmd
        - p1c2-programming-basics.qmd
        - p1c3-data-types.qmd
        - p1c4-data-structures.qmd
        - p1exercises.qmd
    - part: p2-data-acquisition.qmd
      chapters:
        - p2c1-included-datasets.qmd
        - p2c2-import-from-spreadsheets.qmd
        - p2c3-working-with-apis.qmd
        - p2exercises.qmd
    - part: p3-data-preparation.qmd
      chapters: 
        - p3c1-data-cleaning.qmd
        - p3c2-handling-missing-data.qmd
        - p3c3-outliers.qmd
        - p3c4-organizing-data.qmd
        - p3exercises.qmd
    - part: p4-developing-insights.qmd
      chapters:
        - p4c1-summary-statistics.qmd
        - p4c2-regression.qmd
        - p4c3-plotting.qmd
        - p4exercises.qmd
    - part: p5-reporting.qmd
      chapters: 
        - p5c1-spreadsheets.qmd
        - p5c2-r-markdown.qmd
        - p5c3-r-notebook.qmd
        - p5c4-r-shiny.qmd
        - p5exercises.qmd
    - references.qmd

bibliography: references.bib

comments:
  hypothesis: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



