project:
  type: book

book:
  title: "R for Data Analysis"
  author: "Trevor French"
  date: "8/16/2022"
  chapters:
    - part: index.qmd
      chapters:
      - p0c1-what-is-r.qmd
      - p0c2-what-is-data-analysis.qmd
      - p0c3-setup.qmd
    - part: p1-fundamentals.qmd
      chapters:
        - p1c1-r-studio.qmd
        - p1c2-programming-basics.qmd
        - p1c3-data-types.qmd
        - p1c4-data-structures.qmd
    - part: p2-data-acquisition.qmd
      chapters:
        - p2c1-included-datasets.qmd
        - p2c2-import-from-spreadsheets.qmd
        - p2c3-working-with-apis.qmd
    - part: p3-data-preparation.qmd
      chapters: 
        - working-with-csvs.qmd
        - working-with-excel.qmd
        - working-with-dataframes.qmd
    - part: p4-developing-insights.qmd
      chapters: 
        - plotting.qmd
        - summary-statistics.qmd
    - part: p5-reporting.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



