# Part I: Fundamentals

This section will introduce you to the basics of programming in the context of R. There are four chapters in this book. Each chapter has a brief description listed below. After you have finished reading through each of them, you will have the opportunity to attempt practical exercises to reinforce your newly-gained knowledge.

::: callout-note
For users with a moderate amount of experience in R or another programming language feel free to either skip, skim, or leverage this chapter as a reference guide.
:::

- **Getting Familiar with R Studio**- There are four sections in R Studio. These sections are often referred to as "panes". This chapter will introduce you to the "source" pane, "console" pane, "environment" pane, and "files" pane. Additionally, you will learn about the different ways you can customize your version of R Studio such as changing the color scheme.
- **Programming Basics**- While the R language certainly has it's unique advantages, it still leverages principles found in many other programming languages such as functions, comments, and loops. Learn how to apply these and other principles in R.
- **Data Types**- Data is stored differently depending on what it represents when programming. For example, a number is going to be stored as a different data type than a letter is. Learn about the five basic data types in R and how to use them.
- **Data Structures**- In computer science, a data structure refers to the method which one uses to organize their data. There are six basic data structures which are commonly used in R. Learn about each of them in this chapter.